Enhance demo wrappers
Add support for Trace mode and BF16 data type.
Default settings:
        Batch size: ResNet=128, MNIST=64
        Data type: FP32
        Mode: Trace mode

Change-Id: I8423f09b8f4d8e051051f6f937837f0ae5ba40b7
Signed-off-by: Internal Developer <internal-developer@intel.com>

diff --git a/topologies/demo/demo_mnist b/topologies/demo/demo_mnist
--- a/topologies/demo/demo_mnist
+++ b/topologies/demo/demo_mnist
@@ -1,12 +1,18 @@
 #!/bin/bash
 function help()
 {
-        echo -e "help: mnist [arguments]\n"
-        echo -e "  -b <batch_size>,   --batch-size <batchsize>     default: 64"
-        echo -e "  -e <epochs>,       --epochs <epochs>            default: 1"
-        echo -e "  -lr <learning rate >, 		           default: 0.01"
-	echo -e "  -s <seed>,         --seed <seed>                default: None"
-	echo -e "  --num-train-steps <train_step>                  default: maxsize"
+        echo -e "Usage: mnist [arguments]\n"
+        echo -e "  -b <batch_size>,      --batch-size <batchsize>     default: 64"
+        echo -e "  -e <epochs>,          --epochs <epochs>            default: 1"
+        echo -e "  -lr <learning rate >,                              default: 0.01"
+        echo -e "  -s <seed>,            --seed <seed>                default: None"
+        echo -e "                        --mode <mode>                default: trace mode. Possible values: trace, eager"
+        echo -e "  -d <data type>,       --data_type <data type>      default: fp32. Possible values: fp32, bf16"
+        echo -e "                        --num-train-steps <steps>    default: maxsize"
+        echo -e ""
+        echo -e "\nexample:\n"
+        echo -e "./demo_mnist -b 128 --num-train-steps 100 -d fp32 --mode trace"
+        echo -e "./demo_mnist -b 64  --num-train-steps 100 -d bf16 --mode eager"
         echo -e ""
 }
 
@@ -28,6 +34,14 @@ while [ -n "$1" ];
 	-s  | --seed )
             shift
             __seed=$1
+            ;;
+	-d |  --dtype )
+            shift
+            __dtype=$1
+            ;;
+	    --mode )
+            shift
+            __mode=$1
             ;;
         --num-train-steps )
             shift
@@ -52,16 +66,61 @@ LR=${__lr:-0.01}
 SEED_VAL=${__seed:--1}
 TRAIN_STEP=${__train_step:--1}
 
+if [ -n "$__mode" ]; then
+    if [ "$__mode" == "trace" ]; then
+       MODE="--run-trace-mode"
+    elif [ "$__mode" == "eager" ]; then
+       MODE=""
+    else
+       echo "Invalid mode:"$__mode""
+       help
+       exit 1
+    fi
+else
+    MODE="--run-trace-mode"
+    __mode="trace"
+fi
+
+if [ -n "$__dtype" ]; then
+    if [ "$__dtype" == "bf16" ]; then
+       DTYPE="--hmp"
+    elif [ "$__dtype" == "fp32" ]; then
+       DTYPE=""
+    else
+       echo "Invalid data type:"$__dtype""
+       help
+       exit 1
+    fi
+else
+    DTYPE=""
+    __dtype="fp32"
+fi
+
 if [ ${SEED_VAL} -ne -1 ]; then
   SEED="--seed=${SEED_VAL}"
 fi
 if [ ${TRAIN_STEP} -ne -1 ]; then
   NUM_TRAIN_STEP="--num-train-steps=${TRAIN_STEP}"
 fi
-echo -e "Train MNIST with parameters: batch_size: ${BATCH_SIZE} epochs: ${EPOCHS} lr: ${LR} seed: ${SEED_VAL} train_step: ${TRAIN_STEP}"
+
+echo -e "Train MNIST with below parameters:"
+echo -e "batch_size: ${BATCH_SIZE}"
+echo -e "epochs: ${EPOCHS}"
+echo -e "lr: ${LR}"
+echo -e "data_type: "${__dtype}""
+echo -e "Mode: $__mode"
+if [ -n "$SEED" ];then
+    echo -e "seed: ${SEED_VAL}"
+fi
+if [ -n "$NUM_TRAIN_STEP" ];then
+    echo -e "num-train-steps: ${TRAIN_STEP}"
+fi
+
 printf "*** Starting training...\n\n"
-PT_HPU_LOG_MOD_MASK=FFFF PT_HPU_LOG_TYPE_MASK=1 python mnist/main.py --batch-size=${BATCH_SIZE} \
+(set -x;PT_HPU_LOG_MOD_MASK=FFFF PT_HPU_LOG_TYPE_MASK=1 python mnist/main.py --batch-size=${BATCH_SIZE} \
 	--epochs=${EPOCHS} \
 	--lr=${LR} \
 	${SEED} \
-        $NUM_TRAIN_STEP
+        $NUM_TRAIN_STEP \
+        $MODE \
+        $DTYPE)
diff --git a/topologies/demo/demo_resnet b/topologies/demo/demo_resnet
--- a/topologies/demo/demo_resnet
+++ b/topologies/demo/demo_resnet
@@ -6,8 +6,9 @@ function help()
         echo -e "  -m <model>,        --model <model>              default: 'resnet50'"
         echo -e "  -d <device>,       --device <device>            default: 'habana'"
         echo -e "  -b <batch_size>,   --batch-size <batchsize>     default: 128"
+        echo -e "                     --mode <mode>                default: trace mode. Possible values: trace, eager"
+        echo -e "  -d <data type>,    --data_type <data type>      default: fp32. Possible values: fp32, bf16"
         echo -e "  -e <epochs>,       --epochs <epochs>            default: 1"
-        echo -e "  -j <workers>,      --workers <workers>          default: 0"
         echo -e "  --print-freq <print_freq>                       default: 1"
         echo -e ""
 }
@@ -30,6 +31,14 @@ while [ -n "$1" ];
 	-b  | --batch-size )
             shift
             __batch_size=$1
+            ;;
+	-d |  --dtype )
+            shift
+            __dtype=$1
+            ;;
+	    --mode )
+            shift
+            __mode=$1
             ;;
 	-e  | --epochs )
             shift
@@ -64,13 +73,52 @@ EPOCHS=${__epochs:-1}
 WORKERS=${__workers:-0}
 PRINT_FREQ=${__print_freq:-1}
 
+if [ -n "$__mode" ]; then
+    if [ "$__mode" == "trace" ]; then
+       MODE="--run-trace-mode"
+    elif [ "$__mode" == "eager" ]; then
+       MODE=""
+    else
+       echo "Invalid mode:"$__mode""
+       help
+       exit 1
+    fi
+else
+    MODE="--run-trace-mode"
+    __mode="trace"
+fi
+
+if [ -n "$__dtype" ]; then
+    if [ "$__dtype" == "bf16" ]; then
+       DTYPE="--hmp"
+    elif [ "$__dtype" == "fp32" ]; then
+       DTYPE=""
+    else
+       echo "Invalid data type:"$__dtype""
+       help
+       exit 1
+    fi
+else
+    DTYPE=""
+    __dtype="fp32"
+fi
+
+
+echo -e "Train ResNet with below parameters:"
+echo -e "Model: ${MODEL}"
+echo -e "batch_size: ${BATCH_SIZE}"
+echo -e "epochs: ${EPOCHS}"
+echo -e "data_type: "${__dtype}""
+echo -e "Mode: $__mode"
 
 printf "*** Starting training...\n\n"
-PT_HPU_LOG_MOD_MASK=FFFF PT_HPU_LOG_TYPE_MASK=1 python resnet/train.py \
+(set -x; PT_HPU_LOG_MOD_MASK=FFFF PT_HPU_LOG_TYPE_MASK=1 python resnet/train.py \
 	--data-path=${DATA_PATH} \
 	--model=${MODEL} \
 	--device=${DEVICE} \
 	--batch-size=${BATCH_SIZE} \
 	--epochs=${EPOCHS} \
 	--workers=${WORKERS} \
-	--print-freq=${PRINT_FREQ}
+	--print-freq=${PRINT_FREQ} \
+    $MODE \
+    $DTYPE)
